# Generated by Django 5.1.3 on 2025-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
