# Generated by Django 5.1.3 on 2026-05-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_directmessagereaction'),
        ('video', '0010_comment_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='featured_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_by_profiles', to='video.video'),
        ),
    ]
