# Generated by Django 5.1.3 on 2025-03-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='uploader',
        ),
    ]
