# Generated by Django 5.1.3 on 2025-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_commentlike_videolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
