# Generated by Django 5.1.3 on 2025-07-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_video_file_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='file_url',
        ),
    ]
